<section class="savedHiits">
    <section class="records-holder">
        <section>
            <h3 class="total-time">00:00 <span class="span">Mins</span></h3>
        </section>
        <section class="">
            <h3 class="total-hiits">00 <span class="span">Hiits</span></h3>
            <h3 class="total-exercises">00 <span class="span">Exercises</span></h3>
        </section>
    </section>
    <section class="completed-hiits">
        <h3 class="title-finished">Finished Hiits</h3>

        <section class="finished-hiits-holder">

        </section>
    </section>
</section>
