    <section class="exercise-page">
        <h3 class="hiitpage-title"></h3>
        <section class="exercise">
            <section class="hiit-info">
                <p class="exerciseCount"></p>
                <p class="hiitsDuration"></p>
            </section>
            <article class="hiit-desc">
                 
            </article>
            <section class="hiit-exercises">
                
            </section>
        </section>
        
    </section>
