<section class="perform-hiit">
    <section class="exercise-section">
        <h3 class="current-exercise"></h3>
        <h5 class="next-exercise">Next: </h5>
    </section>
        <article class = "current-exercise-description"></article>
    <section class=timer-holder>
    <section class=timer-progress-holder>
        <h1 class="timer">00:00</h1>
    </section>
    </section>
    <h3 class="state-info">
    start
    </h3>
    <section class="timer-buttons">
<label class="switch">
  <input type="checkbox" class="toggle-input">
  <span class="slider round"></span>
  <p> mute </p>
</label>
        <svg class='hidden play' fill=white xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M320-200v-560l440 280-440 280Zm80-280Zm0 134 210-134-210-134v268Z"/></svg>
        <svg class="pause" fill=white xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M520-200v-560h240v560H520Zm-320 0v-560h240v560H200Zm400-80h80v-400h-80v400Zm-320 0h80v-400h-80v400Zm0-400v400-400Zm320 0v400-400Z"/></svg>
        <svg class='restart'fill=white xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="34"><path d="M440-122q-121-15-200.5-105.5T160-440q0-66 26-126.5T260-672l57 57q-38 34-57.5 79T240-440q0 88 56 155.5T440-202v80Zm80 0v-80q87-16 143.5-83T720-440q0-100-70-170t-170-70h-3l44 44-56 56-140-140 140-140 56 56-44 44h3q134 0 227 93t93 227q0 121-79.5 211.5T520-122Z"/></svg>
    </section>
</section>